### ISSUE TITLE
Error seen in SmartThings Live Log, not connecting to the Logstash server

### ISSUE THREAD

**Issue by scordinskyc** [bkeifer/smartthings#1]
org.apache.http.conn.ConnectTimeoutException: Connect to xx.xx.xx.xx:9992 [/xx.xx.xx.xx] failed: connect timed out @ line 163

Nothing is seen on the ELK stack that the SmartApp is pointed to, either.

**Comment by bkeifer** [comment]
This is a network or server issue.  With the address obscured I can't offer any assistance other than the following:  Ensure your logstash instance is actually listening on port 9992 and that connections from the ST cloud are not being prevented by a firewall or IDS/IPS.

**Comment by scordinskyc** [comment]
Thank you for your prompt reply. I can tell you that opening a Telnet connection to my ELK server (from another box) on port 9992 and pasting some json in, it picks it up and deals with it.  Another bloke who wrote on the SmartThings community site on this topic also wrote about this same issue. What can I supply you to give you an idea as to what's up with this?
Thanks,
Christopher

On Fri, Dec 4, 2015 at 11:33 AM -0800, "Brian Keifer" notifications@github.com wrote:

This is a network or server issue.  With the address obscured I can't offer any assistance other than the following:  Ensure your logstash instance is actually listening on port 9992 and that connections from the ST cloud are not being prevented by a firewall or IDS/IPS.

**Comment by bkeifer** [comment]
The box you're using to telnet to the port - is it on the same network as the logstash server or does it have to traverse your logstash server's ISP connection?

You could use something like http://www.canyouseeme.org/ from the logstash server to verify whether or not port 9992 is open to the outside world.  You could also run a packet capture on the logstash server to verify whether or not the connection request is reaching it.

**Comment by scordinskyc** [comment]
So I opened a port on my router and set it to forward to my RPi. Set the SmartApp to use point to my dynamic domain name.  Looks better, just have a “Read time out”.

cc191efe-dae0-4325-bc05-c9417215dbdd https://graph.api.smartthings.com/ide/logs#cc191efe-dae0-4325-bc05-c9417215dbdd 3:28:39 PM EST: error java.net.SocketTimeoutException: Read timed out @ line 163
cc191efe-dae0-4325-bc05-c9417215dbdd https://graph.api.smartthings.com/ide/logs#cc191efe-dae0-4325-bc05-c9417215dbdd 3:28:29 PM EST: debug JSON: {"date":"Fri Dec 04 20:28:29 UTC 2015","name":"power","displayName":"Aeon Home Energy Meter","device":"Aeon Home Energy Meter","deviceId":"6ce13d63-212a-4520-8df3-a544ba6a423b","value":"811","isStateChange":"true","id":"9476195d-9ac5-11e5-8ee8-22000bf9228a","description":"zw device: 1C, command: 3202, payload: 21 74 00 0C 5F 3A 00 00 00 02 1A 2E","descriptionText":"Aeon Home Energy Meter power is 811 W","installedSmartAppId":"null","isoDate":"2015-12-04T20:28:29.467Z","isDigital":"false","isPhysical":"false","location":"Home","locationId":"83082afd-177d-4410-8bac-3013290db018","unit":"W","source":"DEVICE"}

And on the RPi:
2015-12-04T20:27:15.153Z 54.234.229.85 POST / HTTP/1.1

2015-12-04T20:27:15.161Z 54.234.229.85 Accept: _/_

2015-12-04T20:27:15.168Z 54.234.229.85 singularityheader: notxdetect=true

2015-12-04T20:27:15.176Z 54.234.229.85 Content-Length: 613

2015-12-04T20:27:15.184Z 54.234.229.85 Content-Type: application/json

2015-12-04T20:27:15.191Z 54.234.229.85 Host: ***.com:9992

2015-12-04T20:27:15.199Z 54.234.229.85 Connection: Keep-Alive

2015-12-04T20:27:15.204Z 54.234.229.85 User-Agent: Apache-HttpClient/4.3.2 (java 1.5)

2015-12-04T20:27:15.209Z 54.234.229.85 Accept-Encoding: gzip,deflate

2015-12-04T20:27:15.212Z 54.234.229.85 

And on ST’s Live Log:
